// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWHRUU21Tv_gGC3pmth0QvZMGjW9U1VKg',
    appId: '1:629932868335:web:916c285f8fce3e0329d11a',
    messagingSenderId: '629932868335',
    projectId: 'visor-firebase',
    authDomain: 'visor-firebase.firebaseapp.com',
    storageBucket: 'visor-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNxLwAqjae64I8vs0HcdUu-uo7bRGEng0',
    appId: '1:629932868335:android:140fe407b53117ff29d11a',
    messagingSenderId: '629932868335',
    projectId: 'visor-firebase',
    storageBucket: 'visor-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoKITiid8Cm3CGEc4STdpQxTFzvMoHvDI',
    appId: '1:629932868335:ios:1baa552a49687e3e29d11a',
    messagingSenderId: '629932868335',
    projectId: 'visor-firebase',
    storageBucket: 'visor-firebase.appspot.com',
    iosClientId: '629932868335-ve9okgal21vr2jfj7qk778vuecukdruc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoKITiid8Cm3CGEc4STdpQxTFzvMoHvDI',
    appId: '1:629932868335:ios:1baa552a49687e3e29d11a',
    messagingSenderId: '629932868335',
    projectId: 'visor-firebase',
    storageBucket: 'visor-firebase.appspot.com',
    iosClientId: '629932868335-ve9okgal21vr2jfj7qk778vuecukdruc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWHRUU21Tv_gGC3pmth0QvZMGjW9U1VKg',
    appId: '1:629932868335:web:06799a64224d93b229d11a',
    messagingSenderId: '629932868335',
    projectId: 'visor-firebase',
    authDomain: 'visor-firebase.firebaseapp.com',
    storageBucket: 'visor-firebase.appspot.com',
  );
}
